types {
    application/manifest+json webmanifest;
}

server {
    listen 8000;
    server_name _;

    root /var/www/html/public;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
